### ISSUE TITLE
Actors failing dnd5e 2.1.x validation when using Import Book

### ISSUE THREAD

**Issue by rikmarais** [ForgeVTT/forge-compendium-browser#12]
![image](https://user-images.githubusercontent.com/34374883/214733723-b5f5f782-8656-4131-8bdd-dcf231bc546e.png)

FVTT 10.291
dnd5e 2.1.3
compendium-browser 1.3.2
phb 0.3.20

Every one of the errors seems to be on [Actor5e.items], with the specific error being that [FeatData.activation.type]: may not be null
It happens specifically on importBook, and not when importing individual actors. 
The data coming in on the actors seems to be fine and has `FeatData.activation.type` defined, but we get the below error:
```
[KjbN1MfD3mQsypu6] Model Validation Errors
[Actor5e.items]: Model Validation Errors
Model Validation Errors
[BaseItem.system]: Model Validation Errors
[FeatData.activation]: Model Validation Errors
[FeatData.activation.type]: may not be null
```
The effect seems to be that the whole actor won't import.

Switching back over to dnd5e 2.0.3, doing the import, and then going back to dnd5e 2.1.3 and letting the system handle the migration is a workaround

**Comment by kakaroto** [comment]
I believe this was fixed with https://github.com/ForgeVTT/forge-compendium-browser/commit/4ef359f0bb57c8a1e0713c4d64b50c9a587ad9ee
