### ISSUE TITLE
Equipment and condition links to DDB are not linking properly any more.

### ISSUE THREAD

**Issue by ironmonk88** [ForgeVTT/forge-compendium-browser#14]
I believe that D&D Beyond has changed the link urls for equipment etc.  Research the correct link and add to cleanText().

**Comment by kakaroto** [comment]
You shouldn't be seeing those links anymore, since the equipment would be created as an item instead. The new ddb converter will replace all those links in theory

**Comment by rikmarais** [comment]
This no longer appears to be an issue in 1.4.1
