### ISSUE TITLE
v11 will occasionally add a double icon in the manage modules list

### ISSUE THREAD

**Issue by ironmonk88** [ForgeVTT/forge-compendium-browser#19]
Not sure what's going on, but occasionally when you open the Manage Modules config, it will double-up on the Forge compendium icon.

**Comment by rikmarais** [comment]
I haven't been able to replicate this behaviour in 1.4.1

**Comment by illianne** [comment]
✅ Haven't seen this issue on the versions that i've been testing 🙌
