### ISSUE TITLE
[Feature Request] Scene configuration options when importing scenes

### ISSUE THREAD

**Issue by rikmarais** [ForgeVTT/forge-compendium-browser#21]
Feature requested [here](https://forums.forge-vtt.com/t/setting-defaults-loading-content-added-numerous-scenes-to-navigation-bar/90429)

It may be possible to add additional configuration options before the first import that could apply to each scene in the import, to help streamline certain workflows, e.g.
- [ ] Activate/deactivate 'show in navigation' for scenes before import.

**Comment by kakaroto** [comment]
Probably as module settings rather than a prompt during import.

**Comment by ironmonk88** [comment]
Added as module setting.

**Comment by illianne** [comment]
✅ Validated setting both on/off while importing scenes. Working as expected.
