### ISSUE TITLE
Compendium Browser on v10 does not populate individual item/actors/scene pages with respective info

### ISSUE THREAD

**Issue by illianne** [ForgeVTT/forge-compendium-browser#23]
### Steps: 
- create a world on v10
- install relevant modules
- open compendium library
- Navigate to an actor/scene/item etc and click on an individual item

➡️ Result: Nothing displays,
Note: Importing also doesn't work 

<img width="1680" alt="Screen Shot 2023-08-30 at 1 56 16 PM" src="https://github.com/ForgeVTT/forge-compendium-browser/assets/5169836/1cf510fa-0a9e-4ace-9bf3-3e541ceb6bde">

**Comment by ironmonk88** [comment]
Investigated this with Denise and we believe it was due to a compendium being brought from a higher version into a lower version.
Upon reinstalling the compendium it's working again.

I did add a message to the page to indicate when a document hasn't been loaded.

**Comment by illianne** [comment]
✅ Validated this is working as expected. Can move from v10 to v11 without issue, backwards compatibility is a little more sticky needing to reinstall compendium modules.
