### ISSUE TITLE
Investigate Compendium Library module on v9 is not prompting to install 

### ISSUE THREAD

**Issue by illianne** [ForgeVTT/forge-compendium-browser#24]
- create a v9 world
- launch game, navigate to manage modules
- filter for `dnd`
- select one

➡️ Pop up will ask to install dependencies but is missing the compendium browser one
See second image on v10 showing dependencies required including compendium browser

<img width="1680" alt="Screen Shot 2023-08-30 at 2 25 06 PM" src="https://github.com/ForgeVTT/forge-compendium-browser/assets/5169836/a98a6b00-bfe9-40bf-879c-2e269dcd58b3">
<img width="1680" alt="Screen Shot 2023-08-30 at 2 36 11 PM" src="https://github.com/ForgeVTT/forge-compendium-browser/assets/5169836/343bd6e4-b251-4649-b1bf-e5edc616d1b1">

**Comment by kakaroto** [comment]
weird, might be because the module is not installed on v9?

**Comment by illianne** [comment]
✅ Validated this one has been resolved
