### ISSUE TITLE
sub directory class is getting interference from other modules

### ISSUE THREAD

**Issue by ironmonk88** [ForgeVTT/forge-compendium-browser#26]
![image](https://github.com/ForgeVTT/forge-compendium-browser/assets/75920956/23abf5e3-6af1-47da-bf6b-53b1ce37734c)

**Comment by illianne** [comment]
Is there anything I should test on this one @ironmonk88 ?

**Comment by ironmonk88** [comment]
@illianne The module that was causing interference was "Monk's Little Details".
Specifically this setting
![image](https://github.com/ForgeVTT/forge-compendium-browser/assets/75920956/2a065d9d-ae9a-4fb0-9941-c7e9273dec9a)

**Comment by illianne** [comment]
✅ Validated monks little details padding is not affecting the layout/UI of the compendium library
