### ISSUE TITLE
pt-br translation file broken

### ISSUE THREAD

**Issue by kakaroto** [ForgeVTT/forge-compendium-browser#5]
@ironmonk88 not sure what it is you did by renaming the `pt_BR.json` into `pt-BR.json` but you broke the file encoding, it stopped being utf-8, not sure what encoding it is, but it's not recognized anymore as valid.

Weblate refuses to load the json
![image](https://user-images.githubusercontent.com/27990/194698399-1f600055-adc3-4900-a06a-63286a307005.png)

And JDW is the one who noticed the file has a bad encoding.
![image](https://user-images.githubusercontent.com/27990/194698404-1001fe06-05c6-4b5e-953c-bd4080d45a15.png)

If @ironmonk88 isn't available to fix, perhaps @arcanistzed can handle it. Thanks!

**Comment by ironmonk88** [comment]
Foundry viewed the underscore as bad characters and rejected the manifest file. It was expecting the dash.  All I did was rename the file though. I wouldn't have expected that to overwrite.

**Comment by arcanistzed** [comment]
Perhaps the issue is that it looks like you did this via the github.com GUI?

**Comment by arcanistzed** [comment]
Fixed this with bf10f9146405e58b2cc53c51f63e7f71227fdea2. Sorry didn't make a PR because I forgot that github.dev doesn't let you do that. Hopefully it's okay because the changes are small and straightforward.

**Comment by arcanistzed** [comment]
I also switched the line endings from CRLF to LF and applied the same indentation as the `en.json` to the other files.
