### ISSUE TITLE
Additional changes

### ISSUE THREAD

**Issue by ironmonk88** [ForgeVTT/forge-compendium-browser#8]
- [ ] Investigate Icon migration
- [ ] Single import of scene is not linking tokens or notes properly.
- [ ] Should be some sort of progress when creating documents
- [ ] v9 is not linking Actor links in Journal Entries.

**Comment by rikmarais** [comment]
1.4.1 appears to fix single scene imports to an extent.

Single scene import is functional. It imports relevant actors and links them to the tokens on the scene.

**Comment by rikmarais** [comment]
Individual Journal Import is not fully functional. 
- Does not import linked journals.
- Journal name precedes page.
- Viewing journals with Compendium Browser is functional.
